[tool.poetry]
name = "statsbombpy-local"
version = "0.2.1"
description = "statsbombpy uses local open-data"
authors = ["tanzhijian <tanzhijianorg@outlook.com>"]
license = "MIT"
readme = "README.md"
packages = [{include = "statsbombpy_local"}]
homepage = "https://github.com/tanzhijian/statsbombpy-local"
repository = "https://github.com/tanzhijian/statsbombpy-local"

[tool.poetry.dependencies]
python = "^3.10"
statsbombpy = "^1.12.0"
python-dotenv = "^1.0.0"


[tool.poetry.group.dev.dependencies]
pytest = "^7.4.3"
ruff = "^0.1.9"
mypy = "^1.8.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.ruff]
select = ["E", "F", "I"]
line-length = 88

[tool.mypy]
ignore_missing_imports = true
strict = false

[tool.pytest.ini_options]
testpaths = ["tests",]
