name: Lint, Type Check and Test

on:
  push:
    branches: ["main", "dev"]
  pull_request:
    branches: ["main"]

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python: ["3.10"]

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python }}
    - name: Install poetry and dependencies
      run: |
        pip install poetry
        poetry install
    - name: create dotenv
      run: |
        touch .env
        echo "OPEN_DATA_REPO_PATH=foobar" >> .env
    - name: Lint with Ruff
      run: |
        poetry run ruff --format=github --target-version=py310 .
    - name: Type Check with Mypy
      run: |
        poetry run mypy .
    - name: Test with pytest
      run: |
        poetry run pytest
